### ISSUE TITLE
option method not found

### ISSUE THREAD

**Issue by kaushikd49** [prat0318/json_resume#25]
OS - OSX Yosemite. Ruby - ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

Error on running "json_resume --help"
json_resume:27:in `<class:JsonResumeCLI>': undefined method `option' for JsonResumeCLI:Class (NoMethodError)

**Comment by prat0318** [comment]
That's odd. Can you try `gem lock json_resume` and share the results. Here is what i get:
```
(mypy)Prat.local ➜  json_resume git:(master) gem lock json_resume-1.0.4                  [16:06:10]
require 'rubygems'
gem 'json_resume', '= 1.0.4'
gem 'i18n', '= 0.7.0.beta1'
gem 'mustache', '= 0.99.6'
gem 'pdfkit', '= 0.6.2'
gem 'rest-client', '= 1.7.2'
gem 'thor', '= 0.19.1'
gem 'wkhtmltopdf-binary', '= 0.9.9.3'
gem 'mime-types', '= 2.3'
gem 'netrc', '= 0.7.7'
```

**Comment by kaushikd49** [comment]
I get this as the output

require 'rubygems'
# Could not find gem json_resume, try using the full name

**Comment by kaushikd49** [comment]
Installed with ruby 1.9.3p547 and it works fine. So, it seems like it is not compatible with ruby 2.1.2p95's gems.
