### ISSUE TITLE
Changing the locale

### ISSUE THREAD

**Issue by drorata** [prat0318/json_resume#31]
Hi,

I would like to add a new element in the education table (starting year). I managed to do it manually:
- Added the field to the locale `en.yml`
- Created a custom template for HTML

I managed to make it work. However, I would like to develop this further in my fork. To that end, I have a question: 

I installed the tool using the `gem install`. How could I replace this with my fork? How to install/deploy changes that I make in my fork? Sorry for the naive question, I have never wrote anything in Ruby...

**Comment by prat0318** [comment]
i think [PR](https://github.com/prat0318/json_resume/pull/34) sent by you, fixed the issue. Feel free to close the issue :)
