### ISSUE TITLE
Enable using local settings for locale

### ISSUE THREAD

**Issue by drorata** [prat0318/json_resume#35]
Current implementation uses the locale settings as can be found in the gem's directory. This is very limiting and it would be helpful to support custom locales. Probably, the simplest is to use the approach as the one with the templates.

**Comment by drorata** [comment]
Closed with #37

**Comment by drorata** [comment]
@prat0318 Is it pushed automatically to the gems repository?

**Comment by prat0318** [comment]
It's manual for now, but i have pushed the 1.0.6 version. Should be visible now.
